#!/usr/bin/env bash

source ./share/kubevm/version.sh
version="v$_AWSVM_VERSION"

git fetch origin

if [ "$( git tag -l | grep "$version" )" ]; then
  echo "Version $version already pushed"
else
  git tag $version
  git push origin $version:$version
fi
