#!/usr/bin/env bash
# Usage: kubevm create CONFIG
# Summary: Create a config in kubevm
# Help: This command will create a kube configuration in kubevm, and switch to using it.

set -e

if [ -z "$1" ]; then
  echo "No name provided"
  exit 1
fi

__kubevm_config $1

mkdir -p $_KUBEVM_ROOT/$config_path

echo "Creating configuration: $config"
kubevm use $config
echo "Copy your file credentials to ~/.kube and run 'kube help'"
