#!/usr/bin/env bash
set -e

resolve_link() {
  $(type -p greadlink readlink | head -1) "$1"
}

abs_dirname() {
  local cwd="$(pwd)"
  local path="$1"

  while [ -n "$path" ]; do
    cd "${path%/*}"
    local name="${path##*/}"
    path="$(resolve_link "$name" || true)"
  done

  pwd
  cd "$cwd"
}

libexec_path="$(abs_dirname "$0")"
export _KUBEVM_ROOT="$(abs_dirname "$libexec_path")"
export PATH="${libexec_path}:$PATH"

# Include shared files
source $_KUBEVM_ROOT/share/kubevm/version.sh
source $_KUBEVM_ROOT/share/kubevm/config.sh

command="$1"
case "$command" in
"" | "-h" | "--help" )
  exec kubevm-help
  ;;
* )
  command_path="$(command -v "kubevm-$command" || true)"
  if [ ! -x "$command_path" ]; then
    kubevm_config="$(kubevm-list | grep $command || true)"
    if [ ! -z "$kubevm_config" ]; then
      command_path="$(command -v "kubevm-use")"
    else
      echo "kubevm: no such command \`$command'" >&2
      exit 1
    fi
  else
    shift
  fi

  exec "$command_path" "$@"
  ;;
esac
