#!/usr/bin/env bash
# Usage: kubevm edit CONFIG
# Summary: This will open the CONFIG directory in $EDITOR
# Help: This command makes it easy to open up a config directory in your editor

set -e

if [ -z "$1" ]; then
  echo "No name provided"
  exit 1
fi

if [ -z "$EDITOR" ]; then
  echo "You must set \$EDITOR"
  exit 1
fi

__kubevm_config $1

$EDITOR $_KUBEVM_ROOT/$config_path
